name: Hike Fly Competition
favicon: null
layout_spectrum: 0
typography_spectrum: 0.01533
title: 'Lets compare our hike and fly tracks and see what happens '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#626262'
    - '#144d58'
    - '#d9d9d9'
    - '#9e9e9e'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
